### ISSUE TITLE
<stdbool.h> type conversion

### ISSUE THREAD

**Issue by donderom** [scala-interop/slinc#213]
Is there any way to add type conversions between builtin and custom data types?
For example I'm using byte for mapping bool but it would be nice to specify a conversion to/from boolean (by type class?) in the mapping.

**Comment by markehammons** [comment]
I'm going to include a Bool converter in the future (I've been working on the basics so far), but you can create a custom mapping by defining a TypeDescriptor for it. That involves defining a reader/writer and transforms for it. This isn't exactly easy at present, but I'll add something that is more user friendly in the future.

**Comment by donderom** [comment]
It would be nice to be able to define a `TypeDescriptor` for some custom type but at the same it's been only `boolean` I've faced issues with so far.

**Comment by markehammons** [comment]
This can now be done by defining a Transform: 

```scala
given Transform[Boolean, Int](
  i => if i != 0 then true else false,
  b => if b then 1 else 0
)
```

**Comment by donderom** [comment]
All my tests for bools pass, thanks a lot! 👍🏼
